version: '3.8'

services:
  # -------------------------------------------------------------------------
  # 1. Base de Datos (PostgreSQL)
  # -------------------------------------------------------------------------
  postgres:
    image: postgres:14-alpine
    restart: always
    # Mapea el puerto solo si necesitas acceder a él desde tu host (opcional en desarrollo)
    ports:
      - "5432:5432"
    environment:
      # Las variables de la DB son necesarias para la conexión inicial del contenedor
      POSTGRES_PASSWORD: S3cret
      POSTGRES_USER: ventedbuser
      POSTGRES_DB: venteweb
    volumes:
      # Persistencia de datos
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # -------------------------------------------------------------------------
  # 2. Backend (NestJS - Modo Desarrollo con Hot-Reloading)
  # -------------------------------------------------------------------------
  backend:
    build:
      context: ./venteweb
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://ventedbuser:S3cret@postgres:5432/venteweb
    depends_on:
      - postgres
    volumes:
      - ./venteweb/src:/usr/src/app/src
      - ./venteweb/prisma:/usr/src/app/prisma
      - ./venteweb/.env:/usr/src/app/.env
    networks:
      - app-network

  # -------------------------------------------------------------------------
  # 3. Frontend (Angular - Modo Desarrollo con Hot-Reloading)
  # -------------------------------------------------------------------------
  frontend:
    build:
      context: ./ventewebf
      dockerfile: Dockerfile # Usamos el Dockerfile de desarrollo de Angular
    restart: always
    # Angular Dev Server usa 4200 por defecto
    ports:
      - "4200:4200"
    depends_on:
      - backend

    # MONTAJES DE VOLUMEN (CRUCIAL PARA EL DESARROLLO)
    volumes:
      # Monta el código fuente local para hot-reloading
      - ./ventewebf:/app
      # Evita que la carpeta node_modules del contenedor se sobrescriba por el montaje anterior
      - /app/node_modules

    networks:
      - app-network

# -------------------------------------------------------------------------
# Volúmenes y Redes
# -------------------------------------------------------------------------
volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
